repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
- hooks:
  - id: isort
    name: isort (python)
  repo: https://github.com/pycqa/isort
  rev: 5.13.2
- hooks:
  - id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 7.1.0
- hooks:
  - id: black
    language_version: python3.10
  repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.4.2
- hooks:
  - additional_dependencies:
    - tokenize-rt==3.2.0
    args:
    - --strict
    - --ignore-missing-imports
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.27.0
